#!/bin/bash

myupdateline="sudo apt update && sudo apt dist-upgrade -y"
installmypackages="sudo apt install git curl wget zsh nmap"


# git config
myemail="92557089+chrislo95@users.noreply.github.com"

mygitconfigemail="git config --global user.email $myemail"
eval $mygitconfigemail
checkconfigemail="git config --get user.email"
if [[ $(eval $checkconfigemail) == $myemail ]]
then
    echo "Email is correct. Current email is $myemail"
else
    echo "Email is not correct check current email var"   
fi 
eval $checkconfigemail

mygitname="$USER"

mygitconfigname="git config --global user.name $mygitconfigname"
eval $mygitconfigname
if [[ $(eval $mygitconfigname) == $mygitname ]]
then
    echo "Name is correct. Current User is $mygitname"
else
    echo "Name is not correct. Please check current user"
fi
checkconfigname="git config --get user.name"
eval $checkconfigname

ls ~/.ssh/id_ed25519.pub
if [[ $? == 0 ]]
then 
    echo "Key already there"
    sleep 0.5
else
    echo "KEY NOT FOUND. Okay to proceed"
    sleep 0.5
    ssh-keygen -t ed25519 -C $myemail
    echo "KEY BELOW"
    cat ~/.ssh/id_ed25519.pub
fi 

if [[ -f /home/$USER/.vimrc ]]
then
    exit 0
else
    "Vimrc not found. Okay to proceed"
fi 


#
# Install OH MY ZSH
#
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"


#
# ZSH plug ins
#
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install


# Adds Plug.vim manager
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Sets my vimrc file to HOME dic
curl -L https://raw.githubusercontent.com/chrislo95/-scripts/main/vimrcprofile > /home/$USER/.vimrc


